# Generated by Django 2.2 on 2019-05-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normallogin',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
