# Generated by Django 2.2 on 2019-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190505_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='normallogin',
            name='enp_string',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normallogin',
            name='hash_string',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
