# Generated by Django 2.2 on 2019-05-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190507_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='normallogin',
            name='rev_ehval',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
