# Generated by Django 2.2 on 2019-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_normallogin_rev_ehval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normallogin',
            name='rev_ehval',
            field=models.CharField(max_length=300),
        ),
    ]
